exports.comments=()=>{
    return [
    {
        id:1,
        userId:'helloworld',
        date:'2023-08-01',
        comment:'안녕'
    },
    {
        id:2,
        userId:'hellowld',
        date:'2023-08-02',
        comment:'안'
    },
    {
        id:3,
        userId:'hello',
        date:'2023-08-03',
        comment:'오'
    },
    {
        id:4,
        userId:'world',
        date:'2023-08-04',
        comment:'하이'
    }
]
}